name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install g++-10
      run: sudo apt-get update ; sudo apt-get install -y g++-10

    - name: Run make
      run: make
